Stat svc
vasilenkodm/java-explore-with-me pull request #3
Opened 2023-06-15 21:28 UTC by vasilenkodm

2023-06-16 13:30 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть пара замечаний, которые необходимо исправить!

Желаю удачи!

2023-06-16 13:30 UTC, LexLippi commented on stats-service/stats-server/src/main/java/ru/practicum/ewm/repository/StatsRepository.java
> +            "and hit.timestamp <= :end " +
можно использовать оператор `between`

2023-06-16 13:30 UTC, LexLippi commented on stats-service/stats-server/src/main/java/ru/practicum/ewm/repository/StatsRepository.java
> +    List<ViewStats> getStatsNotUnique(@Param(START_PARAM) LocalDateTime start,
Замечания аналогичные запросу выше

2023-06-16 13:30 UTC, LexLippi commented on stats-service/stats-server/src/main/resources/schema.sql
> +    URI             VARCHAR(255) NOT NULL,
Это поле может содержать адреса немного длинее. Универсального ответа нет, но 2048 символов вполне реальный пример

https://www.sistrix.com/ask-sistrix/technical-seo/site-structure/url-length-how-long-can-a-url-be

2023-06-16 20:16 UTC, vasilenkodm commented on stats-service/stats-server/src/main/java/ru/practicum/ewm/controller/StatsController.java
> +    public static final DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern(YYYY_MM_DD_HH_MM_SS);
Нет, смысла нет, FORMATTER используется только здесь.
Замечание ради замечания?

2023-06-16 21:19 UTC, vasilenkodm commented on stats-service/stats-server/src/main/java/ru/practicum/ewm/repository/StatsRepository.java
> +            "and hit.timestamp <= :end " +
Можно, но мне не нужно. Мне удобнее текущее оформление условия.

2023-06-16 21:25 UTC, vasilenkodm commented on stats-service/stats-server/src/main/java/ru/practicum/ewm/repository/StatsRepository.java
> +            "and (:skipURIs = true or hit.uri IN (:uris)) " +
Предлагаю скачать данный проект, убрать "= true" и убедиться, что приложение перестанет запускаться.

2023-06-16 21:27 UTC, vasilenkodm commented on stats-service/stats-server/src/main/java/ru/practicum/ewm/repository/StatsRepository.java
> +    List<ViewStats> getStatsNotUnique(@Param(START_PARAM) LocalDateTime start,
Аналогично ответу выше, предлагаю перепроверить свои предложения.

2023-06-16 21:35 UTC, vasilenkodm commented on stats-service/stats-server/src/main/resources/schema.sql
> +    TIMESTAMP       TIMESTAMP WITHOUT TIME ZONE NOT NULL
SQL прекрасно работает с таким названием колонки.

2023-06-16 21:38 UTC, vasilenkodm commented
К сожалению я не нашел замечаний, которые действительно было необходимо исправить.

2023-06-17 15:27 UTC, LexLippi commented on stats-service/stats-server/src/main/java/ru/practicum/ewm/repository/StatsRepository.java
> +            "and (:skipURIs = true or hit.uri IN (:uris)) " +
Согласен, поспешил, это только с `nativeQuery = true` сработает, потому что это не явный `SQL`-запрос

2023-06-17 15:27 UTC, LexLippi commented on stats-service/stats-server/src/main/resources/schema.sql
> +    URI             VARCHAR(255) NOT NULL,
Например, вот это замечание лично я считаю важным, так как мы существенно ограничиваем количество сайтов с которыми мы работаем.

Ну, ок, давай оставим так

2023-06-17 15:28 UTC, LexLippi commented
Привет!

Хорошая работа!

Я считаю, что одно замечание всё-таки можно было исправить, остальные действительно по желанию, какое именно отписал в MR.

Желаю удачи со следующими частями диплома!

2023-06-17 18:18 UTC, merged